"""Generate the headline CRPSS table (3 trained-prob + post-hoc + 1
classical) and write it as a standalone .tex file ready to \\input into
main.tex.

The trained-probabilistic and classical baselines come from the SwissClim
intercomparison temporal_metrics_combined.csv; the post-hoc baselines
(aifs_perturbed + its Phase 5 IC variant) are read from per-baseline
`crps_line_*_by_lead_ensprob.csv` files because the combined CSV is
regenerated by the slow intercomp pipeline, whereas the per-baseline path
is up-to-date as soon as each baseline's `evaluate_baselines.sh` finishes.

Output: /users/sadamov/pyprojects/ai-models-ensembles/figures/headline_8way_table.tex
"""

from __future__ import annotations
import csv
import json
from pathlib import Path

CSV_COMBINED = "/capstor/store/cscs/mch/s83/sadamov/ai-models-ensembles/baselines/intercomparison/probabilistic/temporal_metrics_combined.csv"
# Exact-WB2 probabilistic-climatology CRPS denominator (lead-resolved),
# crps_clim_eval_<tag>.json: {var_or_var_level: {lead_str: CRPS_clim}}.
CRPS_CLIM = str(Path(__file__).resolve().parent / "data" / "crps_clim_eval_1990_2019.json")
OUT = "/users/sadamov/pyprojects/ai-models-ensembles/figures/headline_8way_table.tex"

AIFS_PERT_PROB = Path(
    "/capstor/store/cscs/mch/s83/sadamov/ai-models-ensembles/baselines/"
    "aifs_perturbed/eval/probabilistic"
)
AIFS_PERT_IC_PROB = Path(
    "/capstor/store/cscs/mch/s83/sadamov/ai-models-ensembles/baselines/"
    "aifs_perturbed_ic/eval/probabilistic"
)

VARS_2D = ["2m_temperature", "mean_sea_level_pressure"]
# IFS-ENS has structural WB2 NaN gaps in ALL surface fields (T2m ~20% NaN,
# MSL ~30% NaN). Excluding MSL but keeping T2m was inconsistent; we now
# include both. The smaller IFS-ENS effective-n for surface vars is
# absorbed by skipna averaging and acknowledged in the caption.
VARS_3D = [
    "geopotential",
    "temperature",
    "u_component_of_wind",
    "v_component_of_wind",
    "specific_humidity",
]
LEADS = [72, 120, 240, 360]

MODELS_FROM_COMBINED = [
    "aifsens",
    "atlas",
    "fcn3",
    "ifs_ens",
    "graphcast_all",
    "aurora_encoder",
    "sfno_modes10",
]
MODELS_FROM_PERBASE = ["aifs_perturbed", "aifs_perturbed_ic"]
MODELS = MODELS_FROM_COMBINED + MODELS_FROM_PERBASE

PRETTY = {
    "aifsens": "AIFS-ENS",
    "atlas": "Atlas",
    "fcn3": "FCN3",
    "ifs_ens": "IFS-ENS",
    "graphcast_all": "graphcast\\_all",
    "aurora_encoder": "aurora\\_encoder",
    "sfno_modes10": "sfno\\_modes10",
    "aifs_perturbed": "aifs\\_perturbed",
    "aifs_perturbed_ic": "aifs\\_perturbed\\_ic",
}

ROLE = {
    "aurora_encoder": "post-hoc",
    "graphcast_all": "post-hoc",
    "sfno_modes10": "post-hoc",
    "aifs_perturbed": "post-hoc",
    "aifs_perturbed_ic": "post-hoc",
    "aifsens": "trained-prob",
    "atlas": "trained-prob",
    "fcn3": "trained-prob",
    "ifs_ens": "classical",
}

crps_clim = json.load(open(CRPS_CLIM))


def clim_for(var: str, lvl: float | None, lead: int) -> float | None:
    """Look up the WB2 probabilistic-climatology CRPS denominator at this lead."""
    key = (
        var
        if var in VARS_2D
        else (f"{var}_{int(lvl)}" if (var in VARS_3D and lvl is not None) else None)
    )
    if key is None or key not in crps_clim:
        return None
    return crps_clim[key].get(str(lead))


data: dict[tuple, float] = {}
with open(CSV_COMBINED) as f:
    for row in csv.DictReader(f):
        if row["metric"] != "CRPS" or row["model"] not in MODELS_FROM_COMBINED:
            continue
        try:
            lead = int(row["lead_time"])
            lvl = float(row["level"]) if row["level"] else None
            val = float(row["value"])
        except ValueError:
            continue
        if lead not in LEADS:
            continue
        data[(row["model"], row["variable"], lead, lvl)] = val


def _load_perbase(root: Path, model: str) -> None:
    """Per-baseline `crps_line_<stem>_by_lead_ensprob.csv` (lead_time_hours, variable, CRPS)."""

    def _load(stem: str, var_label: str, level: float | None) -> None:
        path = root / f"crps_line_{stem}_by_lead_ensprob.csv"
        if not path.exists():
            return
        with open(path) as f:
            for row in csv.DictReader(f):
                try:
                    lead = int(row["lead_time_hours"])
                    val = float(row["CRPS"])
                except ValueError:
                    continue
                if lead not in LEADS:
                    continue
                data[(model, var_label, lead, level)] = val

    for v in VARS_2D:
        _load(v, v, None)
    for v in VARS_3D:
        for lvl in (500, 850):
            _load(f"{v}_{lvl}", v, float(lvl))


_load_perbase(AIFS_PERT_PROB, "aifs_perturbed")
_load_perbase(AIFS_PERT_IC_PROB, "aifs_perturbed_ic")


def crpss(model: str, lead: int) -> float | None:
    per_var = []
    for v in VARS_2D:
        candidates = [
            (k, val) for k, val in data.items() if k[0] == model and k[1] == v and k[2] == lead
        ]
        if not candidates:
            return None
        crps_v = candidates[0][1]
        c = clim_for(v, None, lead)
        if c is None:
            return None
        per_var.append(1 - crps_v / c)
    for v in VARS_3D:
        skills = []
        for lvl in (500.0, 850.0):
            crps_v = data.get((model, v, lead, lvl))
            if crps_v is None:
                continue
            c = clim_for(v, lvl, lead)
            if c is None:
                continue
            skills.append(1 - crps_v / c)
        if not skills:
            return None
        per_var.append(sum(skills) / len(skills))
    if not per_var:
        return None
    return sum(per_var) / len(per_var)


rows = {m: {lead: crpss(m, lead) for lead in LEADS} for m in MODELS}

maxes = {
    lead: max((v for v in (rows[m][lead] for m in MODELS) if v is not None), default=None)
    for lead in LEADS
}

order = sorted(MODELS, key=lambda m: -(rows[m][240] or -99))


def fmt(v: float | None) -> str:
    if v is None:
        return "--"
    s = f"{v:.3f}" if v >= 0 else f"$-${abs(v):.3f}"
    return s


def fmt_bold(v: float | None, lead: int) -> str:
    s = fmt(v)
    if v is None:
        return s
    if maxes[lead] is not None and abs(v - maxes[lead]) < 1e-9:
        return f"\\textbf{{{s}}}"
    return s


lines = []
lines.append("% Headline CRPSS table. Generated from")
lines.append("%   $STORE/baselines/intercomparison/probabilistic/temporal_metrics_combined.csv")
lines.append("% plus per-baseline aifs_perturbed probabilistic CSVs at")
lines.append(f"%   {AIFS_PERT_PROB}")
lines.append("% via tools/headline_8way_table.py.")
lines.append("% 112 inits x 10 members, 7 paper vars (T2m + MSL + Z/T/u/v/q at 500+850 hPa).")
lines.append("% IFS-ENS has WB2-archive NaN gaps in surface fields (T2m ~20%, MSL ~30%); skipna")
lines.append("% averaging absorbs the reduced effective-n. CRPSS = 1 - CRPS/CRPS_clim against the")
lines.append("% WB2 probabilistic climatology (1990-2019 years as members, fair CRPS vs eval")
lines.append("% truth, lead-resolved) -- tools/compute_climatology_crps_vs_eval.py.")
lines.append("")
lines.append("\\begin{table}[t]")
lines.append("  \\centering")
lines.append("  \\small")
lines.append("  \\setlength{\\tabcolsep}{6pt}")
lines.append("  \\caption{Headline CRPSS@(72,120,240,360)h on the production grid")
lines.append("           (112 weekly initialisations $\\times$ 10 members in 2024)")
lines.append("           across the three trained-probabilistic, the post-hoc, and one")
lines.append("           classical baselines. Higher is better; 1 = perfect, 0 =")
lines.append("           climatology, $<0$ = worse than climatology. \\textbf{Bold}")
lines.append("           marks the per-lead optimum. Variable mean over T2m, MSL, $Z$, $T$,")
lines.append("           $u$, $v$, $q$ (latter five at 500 and 850\\,hPa). IFS-ENS surface")
lines.append("           fields have WB2-archive NaN gaps (T2m $\\sim20\\%$, MSL $\\sim30\\%$")
lines.append("           skipna averaging is applied. Derived variables (geopotential")
lines.append("           height, wind speed,")
lines.append("           gradient) excluded because no WB2 climatology reference is")
lines.append("           available for them.}")
lines.append("  \\label{tab:headline8way}")
lines.append("  \\begin{tabular}{@{}l l rrrr@{}}")
lines.append("    \\toprule")
lines.append(
    "    \\textbf{Role} & \\textbf{Model} & \\textbf{72\\,h} & \\textbf{120\\,h} & \\textbf{240\\,h} & \\textbf{360\\,h} \\\\"
)
lines.append("    \\midrule")
group_order = ["trained-prob", "post-hoc", "classical"]
last_role = None
for role_g in group_order:
    for m in order:
        if ROLE[m] != role_g:
            continue
        role_label = {
            "post-hoc": "Post-hoc weight perturbation (this work)",
            "trained-prob": "Trained probabilistic",
            "classical": "Classical reference",
        }[role_g]
        if last_role != role_g:
            lines.append("    \\rowcolor{phaseBg}")
            lines.append(f"    \\multicolumn{{6}}{{@{{}}l}}{{\\textbf{{{role_label}}}}} \\\\")
            last_role = role_g
        cells = [fmt_bold(rows[m][lead], lead) for lead in LEADS]
        lines.append(f"    & {PRETTY[m]} & {cells[0]} & {cells[1]} & {cells[2]} & {cells[3]} \\\\")
    if role_g != group_order[-1]:
        lines.append("    \\hline")
lines.append("    \\bottomrule")
lines.append("  \\end{tabular}")
lines.append("\\end{table}")
Path(OUT).write_text("\n".join(lines) + "\n")
print(f"-> {OUT}")
print("\nFinal table (sorted by CRPSS@240h descending):")
for m in order:
    print(
        f"  {PRETTY[m]:25s}  "
        + "  ".join(
            f"{(rows[m][lead] if rows[m][lead] is not None else float('nan')):.3f}"
            for lead in LEADS
        )
    )
