"""Generate the headline 8-way CRPSS table (9 rows: 4 trained-prob + 4
post-hoc + 1 classical) and write it as a standalone .tex file ready to
\\input into main.tex.

Adds ESFM and aifs_perturbed to the 7-way pattern. ESFM and aifs_perturbed
are read from per-baseline `crps_line_*_by_lead_ensprob.csv` files instead
of from the SwissClim intercomparison temporal_metrics_combined.csv,
because the combined CSV is regenerated by the intercomp pipeline which is
slow to re-run; the per-baseline path is up-to-date as soon as each
baseline's `evaluate_baselines.sh` finishes.

Output: /users/sadamov/pyprojects/ai-models-ensembles/figures/headline_8way_table.tex
"""

from __future__ import annotations
import csv
import json
import math
from pathlib import Path

CSV_COMBINED = "/capstor/store/cscs/mch/s83/sadamov/ai-models-ensembles/baselines/intercomparison/probabilistic/temporal_metrics_combined.csv"
SIGMA = "/iopsstor/scratch/cscs/sadamov/sigma_clim_ablation.json"
OUT = "/users/sadamov/pyprojects/ai-models-ensembles/figures/headline_8way_table.tex"

ESFM_PROB = Path(
    "/capstor/store/cscs/swissai/a122/ESFM_Results/ESFM_s_nm_10ens/"
    "Evaluations_rollout/2023-2024/step10000/probabilistic"
)
AIFS_PERT_PROB = Path(
    "/capstor/store/cscs/mch/s83/sadamov/ai-models-ensembles/baselines/"
    "aifs_perturbed/eval/probabilistic"
)
AIFS_PERT_IC_PROB = Path(
    "/capstor/store/cscs/mch/s83/sadamov/ai-models-ensembles/baselines/"
    "aifs_perturbed_ic/eval/probabilistic"
)
ATMLLM_PROB = Path(
    "/capstor/store/cscs/mch/s83/sadamov/ai-models-ensembles/baselines/" "atmllm/eval/probabilistic"
)

VARS_2D = ["2m_temperature"]  # MSL excluded per the ifs_ens MSL bug
VARS_3D = [
    "geopotential",
    "temperature",
    "u_component_of_wind",
    "v_component_of_wind",
    "specific_humidity",
]
LEADS = [72, 120, 240, 360]

MODELS_FROM_COMBINED = [
    "aifsens",
    "atlas",
    "fcn3",
    "ifs_ens",
    "graphcast_all",
    "aurora_encoder",
    "sfno_modes10",
]
MODELS_FROM_PERBASE = ["esfm", "aifs_perturbed", "aifs_perturbed_ic", "atmllm"]
MODELS = MODELS_FROM_COMBINED + MODELS_FROM_PERBASE

PRETTY = {
    "aifsens": "AIFS-ENS",
    "atlas": "Atlas",
    "fcn3": "FCN3",
    "esfm": "ESFM (step 10k)",
    "ifs_ens": "IFS-ENS",
    "graphcast_all": "graphcast\\_all",
    "aurora_encoder": "aurora\\_encoder",
    "sfno_modes10": "sfno\\_modes10",
    "aifs_perturbed": "aifs\\_perturbed",
    "aifs_perturbed_ic": "aifs\\_perturbed\\_ic",
    "atmllm": "AtmLLM",
}

ROLE = {
    "aurora_encoder": "post-hoc",
    "graphcast_all": "post-hoc",
    "sfno_modes10": "post-hoc",
    "aifs_perturbed": "post-hoc",
    "aifs_perturbed_ic": "post-hoc",
    "aifsens": "trained-prob",
    "atlas": "trained-prob",
    "fcn3": "trained-prob",
    "esfm": "trained-prob",
    "atmllm": "trained-prob",
    "ifs_ens": "classical",
}

sigma = json.load(open(SIGMA))


def sig_for(var: str, lvl: float | None) -> float | None:
    if var in VARS_2D:
        return sigma.get(var)
    if var in VARS_3D and lvl is not None:
        return sigma.get(f"{var}_{int(lvl)}")
    return None


data: dict[tuple, float] = {}
with open(CSV_COMBINED) as f:
    for row in csv.DictReader(f):
        if row["metric"] != "CRPS" or row["model"] not in MODELS_FROM_COMBINED:
            continue
        try:
            lead = int(row["lead_time"])
            lvl = float(row["level"]) if row["level"] else None
            val = float(row["value"])
        except ValueError:
            continue
        if lead not in LEADS:
            continue
        data[(row["model"], row["variable"], lead, lvl)] = val


def _load_perbase(root: Path, model: str) -> None:
    """Per-baseline `crps_line_<stem>_by_lead_ensprob.csv` (lead_time_hours, variable, CRPS)."""

    def _load(stem: str, var_label: str, level: float | None) -> None:
        path = root / f"crps_line_{stem}_by_lead_ensprob.csv"
        if not path.exists():
            return
        with open(path) as f:
            for row in csv.DictReader(f):
                try:
                    lead = int(row["lead_time_hours"])
                    val = float(row["CRPS"])
                except ValueError:
                    continue
                if lead not in LEADS:
                    continue
                data[(model, var_label, lead, level)] = val

    _load("2m_temperature", "2m_temperature", None)
    for v in VARS_3D:
        for lvl in (500, 850):
            _load(f"{v}_{lvl}", v, float(lvl))


_load_perbase(ESFM_PROB, "esfm")
_load_perbase(AIFS_PERT_PROB, "aifs_perturbed")
_load_perbase(AIFS_PERT_IC_PROB, "aifs_perturbed_ic")
_load_perbase(ATMLLM_PROB, "atmllm")


def crpss(model: str, lead: int) -> float | None:
    per_var = []
    for v in VARS_2D:
        candidates = [
            (k, val) for k, val in data.items() if k[0] == model and k[1] == v and k[2] == lead
        ]
        if not candidates:
            return None
        crps_v = candidates[0][1]
        s = sig_for(v, None)
        if s is None:
            return None
        per_var.append(1 - crps_v / (s / math.sqrt(math.pi)))
    for v in VARS_3D:
        skills = []
        for lvl in (500.0, 850.0):
            crps_v = data.get((model, v, lead, lvl))
            if crps_v is None:
                continue
            s = sig_for(v, lvl)
            if s is None:
                continue
            skills.append(1 - crps_v / (s / math.sqrt(math.pi)))
        if not skills:
            return None
        per_var.append(sum(skills) / len(skills))
    if not per_var:
        return None
    return sum(per_var) / len(per_var)


rows = {m: {lead: crpss(m, lead) for lead in LEADS} for m in MODELS}

maxes = {
    lead: max((v for v in (rows[m][lead] for m in MODELS) if v is not None), default=None)
    for lead in LEADS
}

order = sorted(MODELS, key=lambda m: -(rows[m][240] or -99))


def fmt(v: float | None) -> str:
    if v is None:
        return "--"
    s = f"{v:.3f}" if v >= 0 else f"$-${abs(v):.3f}"
    return s


def fmt_bold(v: float | None, lead: int) -> str:
    s = fmt(v)
    if v is None:
        return s
    if maxes[lead] is not None and abs(v - maxes[lead]) < 1e-9:
        return f"\\textbf{{{s}}}"
    return s


lines = []
lines.append("% Headline 8-way CRPSS table. Generated from")
lines.append("%   $STORE/baselines/intercomparison/probabilistic/temporal_metrics_combined.csv")
lines.append("% plus per-baseline ESFM + aifs_perturbed probabilistic CSVs at")
lines.append(f"%   {ESFM_PROB}")
lines.append(f"%   {AIFS_PERT_PROB}")
lines.append("% via tools/headline_8way_table.py.")
lines.append("% 112 inits x 10 members, 7 paper vars (MSL EXCLUDED due to ifs_ens MSL bug,")
lines.append("% see memory ifs-ens-msl-bug.md; re-run after patch). CRPSS = 1 - CRPS/CRPS_clim")
lines.append("% against analytical Gaussian climatology from WB2 2022-2024.")
lines.append("")
lines.append("\\begin{table}[t]")
lines.append("  \\centering")
lines.append("  \\small")
lines.append("  \\setlength{\\tabcolsep}{6pt}")
lines.append("  \\caption{Headline CRPSS@(72,120,240,360)h on the production grid")
lines.append("           (112 weekly initialisations $\\times$ 10 members in 2024)")
lines.append("           across the four trained-probabilistic, four post-hoc, and one")
lines.append("           classical baselines. Higher is better; 1 = perfect, 0 =")
lines.append("           climatology, $<0$ = worse than climatology. \\textbf{Bold}")
lines.append("           marks the per-lead optimum. MSL excluded due to an IFS-ENS MSL bug")
lines.append("           (see Sec.~\\ref{sec:methods-eval}); re-run with the patched data")
lines.append("           is pending. Derived variables (geopotential height, wind speed,")
lines.append("           gradient) excluded because no WB2 climatology $\\sigma$ is")
lines.append("           available for them. ESFM \\citep{Ozdemir2026esfm} reports the")
lines.append("           training-step-10000 checkpoint of ESFM\\_s\\_nm\\_10ens, an")
lines.append("           intermediate ensemble-finetune snapshot rather than a fully")
lines.append("           trained production model.}")
lines.append("  \\label{tab:headline8way}")
lines.append("  \\begin{tabular}{@{}l l rrrr@{}}")
lines.append("    \\toprule")
lines.append(
    "    \\textbf{Role} & \\textbf{Model} & \\textbf{72\\,h} & \\textbf{120\\,h} & \\textbf{240\\,h} & \\textbf{360\\,h} \\\\"
)
lines.append("    \\midrule")
group_order = ["trained-prob", "post-hoc", "classical"]
last_role = None
for role_g in group_order:
    for m in order:
        if ROLE[m] != role_g:
            continue
        role_label = {
            "post-hoc": "Post-hoc weight perturbation (this work)",
            "trained-prob": "Trained probabilistic",
            "classical": "Classical reference",
        }[role_g]
        if last_role != role_g:
            lines.append("    \\rowcolor{phaseBg}")
            lines.append(f"    \\multicolumn{{6}}{{@{{}}l}}{{\\textbf{{{role_label}}}}} \\\\")
            last_role = role_g
        cells = [fmt_bold(rows[m][lead], lead) for lead in LEADS]
        lines.append(f"    & {PRETTY[m]} & {cells[0]} & {cells[1]} & {cells[2]} & {cells[3]} \\\\")
    if role_g != group_order[-1]:
        lines.append("    \\hline")
lines.append("    \\bottomrule")
lines.append("  \\end{tabular}")
lines.append("\\end{table}")
Path(OUT).write_text("\n".join(lines) + "\n")
print(f"-> {OUT}")
print("\nFinal table (sorted by CRPSS@240h descending):")
for m in order:
    print(
        f"  {PRETTY[m]:25s}  "
        + "  ".join(
            f"{(rows[m][lead] if rows[m][lead] is not None else float('nan')):.3f}"
            for lead in LEADS
        )
    )
