"""LaTeX table for the out-of-sample runner-up validation (review item 3).

The ablation picks a production baseline from four initialisations, where cells
within about +-0.02 CRPSS are not separable. This scores each winner against its
closest rivals on the independent 112-init grid, restricted to the
initialisations the pair has in common so the comparison is strictly paired.

An arm short of the full grid is reported as (pending) rather than scored: a
rival evaluated on fewer initialisations is not comparable with the headline.
"""

import argparse
import csv
import json
import collections

from _env import STORE

WINNERS = {
    "aurora_encoder": ["aurora_enc_s044"],
    "graphcast_all": ["graphcast_m2g", "graphcast_g2m"],
    "sfno_modes10": ["sfno_enc_s054", "sfno_enc_s035"],
    "aifs_perturbed": ["aifs_all_s010"],
}
PRETTY = {
    "aurora_encoder": "aurora\\_encoder",
    "graphcast_all": "graphcast\\_all",
    "sfno_modes10": "sfno\\_modes10",
    "aifs_perturbed": "aifs\\_perturbed",
    "aurora_enc_s044": "aurora enc $\\sigma$=0.044",
    "graphcast_m2g": "graphcast m2g",
    "graphcast_g2m": "graphcast g2m",
    "sfno_enc_s054": "sfno enc $\\sigma$=0.054",
    "sfno_enc_s035": "sfno enc $\\sigma$=0.035",
    "aifs_all_s010": "aifs all $\\sigma$=0.01",
}
GROUPS = [
    ["2m_temperature"],
    ["mean_sea_level_pressure"],
    ["geopotential_500", "geopotential_850"],
    ["temperature_500", "temperature_850"],
    ["u_component_of_wind_500", "u_component_of_wind_850"],
    ["v_component_of_wind_500", "v_component_of_wind_850"],
    ["specific_humidity_500", "specific_humidity_850"],
]

ap = argparse.ArgumentParser()
ap.add_argument(
    "--csv",
    default=str(STORE / "analysis/per_init_crps_production_v2.csv"),
)
ap.add_argument("--clim", default="tools/data/crps_clim_eval_1990_2019_per_init.json")
ap.add_argument("--out", default="figures/rival_validation_table.tex")
ap.add_argument("--require-inits", type=int, default=112)
a = ap.parse_args()

clim = json.load(open(a.clim))
crps = collections.defaultdict(
    lambda: collections.defaultdict(lambda: collections.defaultdict(dict))
)
for r in csv.DictReader(open(a.csv)):
    ch = r["variable"] + ("" if not r["level"] else "_" + r["level"])
    crps[r["baseline"]][r["lead"]][ch][r["init"]] = float(r["crps"])


def crpss(model, lead, inits):
    gv = []
    for chans in GROUPS:
        cv = [
            1 - sum(crps[model][lead][c][i] for i in inits) / sum(clim[c][lead][i] for i in inits)
            for c in chans
        ]
        gv.append(sum(cv) / len(cv))
    return sum(gv) / len(gv)


LEADS = ["120", "240"]
lines = [
    "% generated by tools/make_rival_validation_table.py -- do not edit by hand",
    r"\begin{table}[!htbp]",
    r"  \centering \small",
    r"  \setlength{\tabcolsep}{5pt}",
    r"  \renewcommand{\arraystretch}{1.15}",
    r"  \caption{Out-of-sample validation of the runner-up configurations. Each "
    r"production baseline is scored against the ablation cells that fell within the "
    r"$\pm0.02$ CRPSS band of it, on the independent 112-init grid and on the "
    r"initialisations the pair has in common. $\Delta$ is rival minus winner, so a "
    r"positive value would mean the ablation picked the weaker cell. The selection "
    r"criterion is CRPSS at 240\,h (sec.~\ref{sec:methods-phases}).}",
    r"  \label{tab:rival-validation}",
    r"  \begin{tabular}{@{}l l r rr rr@{}}",
    r"    \toprule",
    r"    & & & \multicolumn{2}{c}{\textbf{120\,h}} & \multicolumn{2}{c}{\textbf{240\,h}} \\",
    r"    \cmidrule(lr){4-5} \cmidrule(lr){6-7}",
    r"    \textbf{Winner} & \textbf{Rival} & \textbf{$n$} & "
    r"\textbf{winner} & \textbf{$\Delta$} & \textbf{winner} & \textbf{$\Delta$} \\",
    r"    \midrule",
]
n_pending = 0
for win, rivals in WINNERS.items():
    for j, riv in enumerate(rivals):
        head = PRETTY[win] if j == 0 else ""
        have = {m: len(crps[m]["240"].get("2m_temperature", {})) for m in (win, riv)}
        if min(have.values()) < a.require_inits:
            lines.append(
                rf"    {head} & {PRETTY[riv]} & {min(have.values())} & "
                r"\multicolumn{4}{c}{(pending)} \\"
            )
            n_pending += 1
            continue
        common = sorted(
            set(crps[win]["240"]["2m_temperature"]) & set(crps[riv]["240"]["2m_temperature"])
        )
        cells = []
        for L in LEADS:
            w, r_ = crpss(win, L, common), crpss(riv, L, common)
            cells += [f"{w:.3f}", f"{r_-w:+.4f}"]
        lines.append(rf"    {head} & {PRETTY[riv]} & {len(common)} & " + " & ".join(cells) + r" \\")
    lines.append(r"    \addlinespace")
lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}"]
open(a.out, "w").write("\n".join(lines) + "\n")
print(f"wrote {a.out} ({n_pending} pending row(s))")
