"""LaTeX table for the IC-versus-weight spread attribution (review item 1).

Reads ic_weight_decomposition.py's CSV and emits the appendix table. Uses the
spread_rms column (sqrt of the mean variance): variances are what add when two
perturbation sources are independent, so a mean of per-pixel standard deviations
would bias the additivity ratio upward (Minkowski) and overstate independence.
"""

import argparse
import csv
import collections

ap = argparse.ArgumentParser()
ap.add_argument("--csv", default="tools/data/ic_decomp_4bb.csv")
ap.add_argument("--out", default="figures/ic_decomp_table.tex")
ap.add_argument("--leads", nargs="+", type=int, default=[6, 24, 72, 120, 240])
a = ap.parse_args()

d = collections.defaultdict(dict)
n_inits = set()
for r in csv.DictReader(open(a.csv)):
    ch = r["variable"] + ("" if not r["level"] else "_" + r["level"])
    d[(r["baseline"], ch, int(r["lead"]))][r["arm"]] = float(r["spread_rms"])
    n_inits.add(int(r["n_inits"]))
chans = sorted({k[1] for k in d})
assert len(n_inits) == 1, f"arms differ in init count: {sorted(n_inits)}"
N = n_inits.pop()


def agg(bb, lead, fn):
    v = [
        fn(*(d[(bb, c, lead)][k] for k in ("weight", "ic", "weight+ic")))
        for c in chans
        if len(d.get((bb, c, lead), {})) == 3
    ]
    return sum(v) / len(v)


rows = []
for bb, label in (
    ("aurora", "Aurora"),
    ("graphcast", "GraphCast"),
    ("sfno", "SFNO"),
    ("aifs", "AIFS"),
):
    if not any(k[0] == bb for k in d):
        continue
    wt = [agg(bb, L, lambda w, i, b: 100 * w * w / (b * b)) for L in a.leads]
    ic = [agg(bb, L, lambda w, i, b: 100 * i * i / (b * b)) for L in a.leads]
    ra = [agg(bb, L, lambda w, i, b: b * b / (w * w + i * i)) for L in a.leads]
    rows.append((label, wt, ic, ra))

L = a.leads
out = []
out.append("% generated by tools/make_ic_decomp_table.py -- do not edit by hand")
out.append(r"\begin{table}[!htbp]")
out.append(r"  \centering \small")
out.append(r"  \setlength{\tabcolsep}{5pt}")
out.append(r"  \renewcommand{\arraystretch}{1.15}")
out.append(
    r"  \caption{Attribution of ensemble variance to the weight and "
    r"initial-condition perturbations, on the " + str(N) + r" production "
    r"initialisations present in all three arms of every backbone. Each entry "
    r"is the mean over the twelve (variable, level) channels of the cos-lat "
    r"weighted variance, so the additivity ratio is exact rather than biased by "
    r"averaging standard deviations. Rows: the share of the combined weight+IC "
    r"variance that each arm reaches alone, and the ratio "
    r"$\sigma^2_\text{wt+ic} / (\sigma^2_\text{wt} + \sigma^2_\text{ic})$, "
    r"which equals 1 when the two sources are independent and falls below 1 as "
    r"both saturate toward the climatological variance.}"
)
out.append(r"  \label{tab:ic-decomp}")
out.append(r"  \begin{tabular}{@{}l l " + "r" * len(L) + r"@{}}")
out.append(r"    \toprule")
out.append(
    r"    \textbf{Backbone} & \textbf{Quantity} & "
    + " & ".join(rf"\textbf{{{x}\,h}}" for x in L)
    + r" \\"
)
out.append(r"    \midrule")
for label, wt, ic, ra in rows:
    out.append(
        rf"    {label} & weight-only (\% of wt+IC) & " + " & ".join(f"{v:.0f}" for v in wt) + r" \\"
    )
    out.append(r"     & IC-only (\% of wt+IC) & " + " & ".join(f"{v:.0f}" for v in ic) + r" \\")
    out.append(r"     & additivity ratio & " + " & ".join(f"{v:.3f}" for v in ra) + r" \\")
    if label != rows[-1][0]:
        out.append(r"    \addlinespace")
out.append(r"    \bottomrule")
out.append(r"  \end{tabular}")
out.append(r"\end{table}")
open(a.out, "w").write("\n".join(out) + "\n")
print(f"wrote {a.out} ({len(rows)} backbones, n={N})")
