#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Compute the 1-Wasserstein distance (W1, wd_kde module) for the 6 production
# baselines that currently lack a wd_kde Wasserstein CSV, so the production
# all-metrics Table C1 has a complete W1 column.
#
# aifs_perturbed already has its CSV
# ($STORE/baselines/aifs_perturbed/eval/wd_kde/wd_kde_wasserstein_averaged_enspooled.csv);
# this run covers the other six and does NOT touch it.
#
# wd_kde-ONLY: all other modules disabled in eval_wd_kde_only_w1_config.yaml
# (pre-generated by the setup step). Lead-resolved (stride 6h over 0..360h) so
# the 120 h and 240 h rows are both present. Output goes to the standard path
#   $STORE/baselines/<model>/eval/wd_kde/wd_kde_wasserstein_averaged_enspooled.csv
#
# Usage: sbatch tools/submit_w1_wdkde.sh
# ---------------------------------------------------------------------------
#SBATCH --job-name=w1_wdkde_baselines
#SBATCH --account=a122
#SBATCH --partition=normal
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=128
#SBATCH --mem=320G
#SBATCH --time=06:00:00
#SBATCH --output=/capstor/store/cscs/mch/s83/sadamov/ai-models-ensembles/baseline_eval_logs/w1_wdkde_baselines_%j.out
#SBATCH --error=/capstor/store/cscs/mch/s83/sadamov/ai-models-ensembles/baseline_eval_logs/w1_wdkde_baselines_%j.err

set -euo pipefail

STORE="/capstor/store/cscs/mch/s83/sadamov/ai-models-ensembles"
SRC_DIR="/users/sadamov/pyprojects/ai-models-ensembles"

export PYTHONUNBUFFERED=1
export TMPDIR="/iopsstor/scratch/cscs/sadamov/tmp"
export DASK_TEMPORARY_DIRECTORY="/iopsstor/scratch/cscs/sadamov/tmp"
mkdir -p "$TMPDIR"

source "${SRC_DIR}/.venv/bin/activate"
export SSL_CERT_FILE="$(python -c 'import certifi; print(certifi.where())')"

MODELS="aifsens atlas fcn3 graphcast_all aurora_encoder sfno_modes10"

for model in $MODELS; do
    cfg="$STORE/baselines/${model}/eval_wd_kde_only_w1_config.yaml"
    echo "===== [$(date -u +%H:%M:%S)] wd_kde (W1) for ${model} -> ${cfg} ====="
    if [[ ! -f "$cfg" ]]; then
        echo "MISSING config $cfg -- skipping ${model}" >&2
        continue
    fi
    python -m swissclim_evaluations.cli --config "$cfg"
    echo "===== [$(date -u +%H:%M:%S)] done ${model} ====="
done

echo "ALL DONE"
