#!/usr/bin/env bash
# Re-run ONLY the energy_spectra module for the ablation runs behind Tab. 4
# (figures/calibration_basis_table.tex), after the SwissClim member-0 align fix
# (SwissClim_Evaluations 9d3a7fd). The existing per-run eval config is reused
# with every other module switched off, so the output lands in the same
# eval/<run_tag>/energy_spectra/ dir the table generator reads. The previous
# (member-0) outputs are archived next to it, never deleted.
#
# Usage:  bash tools/submit_ablation_spectra_reeval.sh
set -euo pipefail
STORE="${AIENS_STORE:-/capstor/store/cscs/mch/s83/sadamov/ai-models-ensembles}"
SRC_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PY="$SRC_DIR/.venv/bin/python3"
LOG_DIR="$STORE/ablation_logs"
STAMP="member0_pre_2026-09-17"

RUNS=(
  phase1/aurora/mag_0.03_layer_all
  phase2/aurora/mag_0.044176_layer_encoder
  phase2b/aurora/mag_0.025_layer_encoder
  phase3/aurora/mag_0.40_layer_unet_bottom
  phase3b/aurora/mag_0.015_layer_enc_012
  phase1/graphcast_operational/mag_0.01_layer_all
  phase2/graphcast_operational/mag_0.029665_layer_m2g
  phase2b/graphcast_operational/mag_0.014_layer_g2m
  phase3/graphcast_operational/gcsigma_1.0_gcnodes42_frozen
  phase3b/graphcast_operational/gcsigma_0.159_gcnodes162_frozen
  phase1/sfno/mag_0.03_layer_all
  phase2/sfno/mag_0.053852_layer_encoder
  phase2b/sfno/mag_0.035_layer_encoder
  phase3/sfno/mag_0.25_modes10
  phase3b/sfno/mag_0.035_modes20
  phase1/aifs/mag_0.01_layer_all
  phase2/aifs/mag_0.027500_layer_decoder
)

for r in "${RUNS[@]}"; do
  if [[ -n "${ONLY:-}" ]]; then
    keep=0; for o in $ONLY; do [[ "$r" == *"$o"* ]] && keep=1; done; [[ $keep -eq 1 ]] || continue
  fi
  phase="${r%%/*}"; rest="${r#*/}"; model="${rest%%/*}"; run="${rest#*/}"
  base="$STORE/ablation/$phase/$model"
  eval_root="$base/eval/$run"
  src_cfg="$base/eval/${run}_config.yaml"
  dst_cfg="$base/eval/${run}_energy_spectra_only_config.yaml"
  [[ -f "$src_cfg" ]] || { echo "MISSING config: $src_cfg"; exit 1; }
  if [[ -d "$eval_root/energy_spectra" ]]; then
    if [[ -d "$eval_root/energy_spectra_$STAMP" ]]; then
      # archive already taken: this is a partial output of a preempted/failed
      # re-eval attempt, regenerable, so drop it (never the forecast.zarr)
      echo "  dropping partial re-eval output: $eval_root/energy_spectra"
      rm -rf "$eval_root/energy_spectra"
    else
      mv "$eval_root/energy_spectra" "$eval_root/energy_spectra_$STAMP"
    fi
  fi
  "$PY" - "$src_cfg" "$dst_cfg" "$base" "$run" "$eval_root" <<'PYE'
import glob, sys, yaml
src, dst, base, run, eval_root = sys.argv[1:6]
c = yaml.safe_load(open(src))
# The stored configs are historical: some predate the 2026-05-30 store move
# (swissai/a122), the phase2c -> phase2b dir rename, or a run-tag rename
# (layer_coarse_encoder -> layer_unet_bottom). Rebuild the prediction paths
# from what is on disk under the current run dir instead of trusting them.
ml = sorted(glob.glob(f"{base}/*/{run}/forecast.zarr"))
assert len(ml) == 4, (run, ml)
c["paths"]["ml"] = ml
c["paths"]["output_root"] = eval_root
c["modules"] = {k: (k == "energy_spectra") for k in c["modules"]}
# Some stored configs were regenerated by later eval vintages with
# energy_spectra: mean (phase1/aurora); the table is the pooled quantity.
c["selection"]["ensemble"]["energy_spectra"] = "pooled"
# Only the LSD CSVs feed Tab. 4; skip plots/npz/spectrograms so the job fits
# inside a preemption window.
c["plotting"]["output_mode"] = "none"
c["plotting"]["energy_spectra_spectrogram"] = False
with open(dst, "w") as f:
    yaml.safe_dump(c, f, sort_keys=False)
PYE
  tag="spectra_reeval_${phase}_${model}_${run}"
  jid=$(sbatch --parsable --job-name="$tag" --partition="${PARTITION:-normal}" --account=ab016 \
        --nodes=1 --ntasks=1 --exclusive --requeue --cpus-per-task=144 --mem=800G --time=04:00:00 \
        --output="$LOG_DIR/${tag}_%j.out" --error="$LOG_DIR/${tag}_%j.err" \
        --wrap="source ${SRC_DIR}/.venv/bin/activate && python -m swissclim_evaluations.cli --config '${dst_cfg}'")
  echo "$jid  $r"
done
